[package]
name = "day02"
version = "0.1.0"
authors = ["Tor Arvid Lund <tor.arvid.lund@kolonial.no>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.2"
