[package]
name = "day18"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
itertools = "0.10.1"
lazy_static = "1.4.0"
eval = "0.4.3"
nom = "7.1.0"
